name: Deploy Docs (main/dev) to GitHub Pages

on:
  push:
    branches:
      - main
      - dev

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: |
          npm run prebuild
          npm run build

      - name: Checkout existing gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages
          fetch-depth: 0
        continue-on-error: true  # 初回デプロイ時に存在しない場合でもOK

      - name: Copy built docs into gh-pages
        run: |
          mkdir -p gh-pages
          if [ "${{ github.ref_name }}" = "main" ]; then
            cp -r docs/* gh-pages/
          else
            mkdir -p gh-pages/dev
            rm -rf gh-pages/dev/*
            cp -r docs/* gh-pages/dev/
          fi

      - name: Commit and push to gh-pages
        run: |
          cd gh-pages
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Deploy from ${{ github.ref_name }} branch" || echo "No changes to commit"
          git branch -M gh-pages
          git push origin gh-pages